[package]
name = "crates-io"
version = "0.1.0"
authors = ["MesaTEE Authors"]
edition = "2018"

[dependencies]

base64               = "0.10.1"
bit-vec              = "0.6.1"
bytes                = "0.4.12"
cfg-if               = "0.1.9"
clap_flags           = "0.2.0"
ctrlc                = "3.1.2"
env_logger           = "0.7.1"
exitfailure          = "0.5.1"
failure              = "0.1.5"
httparse             = "1.3.2"
indexmap             = "1.0"
log                  = "0.4.6"
nan-preserving-float = "0.1.0"
net2                 = "0.2.33"
num-bigint           = "0.2.2"
prost                = "0.5.0"
prost-build          = "0.5.0"
prost-derive         = "0.5.0"
prost-types          = "0.5.0"
quicli               = "0.4.0"
rand                 = "0.7.0"
rand_core            = "0.4"
rdrand               = "0.6"
rustls               = "0.16.0"
serde                = "1.0.92"
serde_derive         = "1.0.92"
serde_json           = "1.0.39"
structopt            = "0.2.16"
threadpool           = "1.0"
toml                 = "0.5.1"
uuid                 = { version = "0.7.4", features = ["serde", "v4"] }
wabt                 = "0.4.0"
webpki               = "0.21.0"
webpki-roots         = "0.17.0"
yasna                = "0.3.0"

sgx_cov              = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
sgx_tcrypto          = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
sgx_tse              = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
sgx_tstd             = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
sgx_urts             = { git = "https://github.com/baidu/rust-sgx-sdk", rev = "v1.0.9" }
